version: "3.9"

services:
  backend:
    build:
      context: .

  nginx:
    image: nginx:latest
    ports:
      - "80:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
